### ISSUE TITLE
Issue with 'dconf' attribute with 'DeckManager' object?

### ISSUE THREAD

**Issue by skiplesions** [eshapard/Anki-avgEase#5]
I have been receiving this message every time I open Anki. Not sure how to fix on my own.

```
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-11 22:38:39

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "aqt\main.py", line 162, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 199, in setupProfile
  File "aqt\main.py", line 398, in loadProfile
  File "aqt\gui_hooks.py", line 1559, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "C:\Users\Jr\AppData\Roaming\Anki2\addons21\633293039\__init__.py", line 83, in update_ease_factors
    dconf = mw.col.decks.dconf
AttributeError: 'DeckManager' object has no attribute 'dconf'
```

**Comment by eshapard** [comment]
Must be incompatible with Anki 2.1.24. 'dconf' must have been renamed or 
moved or something.

Excerpts from skiplesions's message of May 12, 2020 5:56 am:

**Comment by DrewSSP** [comment]
The issue persists with Anki 2.1.28

**Comment by Rupeeee** [comment]
eshapard do you plan to update this add on? Would be fantastic if you did since it's such a good idea, and would be so useful to lots of anki users.
All the best!

ps, here's the report that came up when I just tried installing it: 
Anki 2.1.36 (c505894b) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-27 18:39:10
Add-ons possibly involved: ⁨avgEase⁩

**Comment by eshapard** [comment]
Sorry, I no longer use Anki, so I won't be updating any of my addons.

**Comment by Rupeeee** [comment]
Fair dos, thanks for getting back to me 😀
